version: "3"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      {piwik-path-html}
      - /var/run/docker.sock:/tmp/docker.sock
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/vhost.d:/etc/nginx/vhost.d
      - ./conf/certs:/etc/nginx/certs  
    network_mode: "bridge"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10" 
