version: "3"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      {piwik-path-html}
      - /var/run/docker.sock:/tmp/docker.sock
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/vhost.d:/etc/nginx/vhost.d
      - ./conf/certs:/etc/nginx/certs  
      - ./html:/usr/share/nginx/html
    networks:
      - nginx
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10" 
    command: /bin/bash -c "rm -f /etc/nginx/conf.d/default.conf && echo 'Sleep 10' && sleep 10 && forego start -r"
    deploy:
       resources:
         limits:
           cpus: '1.0'
           memory: 100m

networks:
   nginx:
      external: true
