version: "2"

services:
  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./conf/conf.d:/etc/nginx/conf.d
      - ./conf/vhost.d:/etc/nginx/vhost.d
      - ./conf/certs:/etc/nginx/certs  
    network_mode: "bridge"
